name: "Install Skopeo"
description: "Install Skopeo with version input support."
author: "Jetsung Chan"
branding:
  icon: "zap"
  color: "blue"
inputs:
  version:
    description: "Skopeo version (e.g. 1.12.0, latest). Leave empty for latest stable."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: "Install Skopeo"
      shell: bash
